### ISSUE TITLE
fimware gets stuck.

### ISSUE THREAD

**Issue by Atntias** [ErikZalm/Marlin-non-gen6#2]
im using gen3+ setup, with Marlin 0.9.7L and pronterface and sfact, and when ever i start a print it executes the first 2 commands then stops. then i have to disconnect and reconnect agian to get a response from the machine.
when telling the machine to move not in print, works nice, but sometimes get stuck also and have to reconnect. cant figure out what triggers it, but in print it happens every time.
i thought it might be a communaction problem so i took the speed down to 115200 - no effect.

**Comment by Jaydmdigital** [comment]
Can you confirm if you are using Monitor mode in Pronterface when printing? If so, try it with it off.

**Comment by Atntias** [comment]
ok so here what i could get:

when gets stuck i get the line twice and then silence (reset?)
 "Serial Error: Line Number is not Last Line Number+1, Last Line:0 
Resend:1"

when i start to print the first 2 command execute (goes up on z and retract with extruder then stuck)
if i pause it on pronterface then try tell it to move, pronterface crashes.
if i simply disconnect and reconnect machine goes online and can move agian. so this seems like software reset?
for debugging nothing comes out except for the temp, but thats not helpfull.
i tried to delete the first gcode lines see if its s specific gcode gets it stuck. but its not, it just get stuck on the 2nd line always.

if i play with the jog it works but sometimes get reset randomly. sometimes issuing the welcome message.

any tests i shuold make?!

**Comment by Jaydmdigital** [comment]
Does Sprinter work with you Pronterface? Do you have the most up-to-date Pronterface? What OS?

**Comment by Atntias** [comment]
yes it does, i do have latest pronterface, win7 os.

oops sory for closeing then reopeing mistake...

**Comment by Jaydmdigital** [comment]
can you pastebin your configuration.h file?

**Comment by Atntias** [comment]
http://pastebin.com/XgJ3mE7R

**Comment by Jaydmdigital** [comment]
In your configuration.h you have:

...
// Gen 3 Plus = 21
// gen 3  Monolithic Electronics = 22
#define MOTHERBOARD 21

But in pins.h I do not see MOTHERBOARD == 21 and thus no pins defined.

You should copy the section from https://github.com/kliment/Sprinter/blob/master/Sprinter/pins.h to your pins.h for MOTHERBOARD == 21   (starting on line 207 to 265)

-Jay

**Comment by Atntias** [comment]
i did have that conifugred, i now can verfiy that the board resets!, i used m92 code to change steps per unit and after getting "stuck" and reconnecting the unit per axis goes back to default - that means it resets for sure.

**Comment by Pointedstick** [comment]
I have the same issue. What's interesting is that my first print with Marlin was wonderful (see http://forums.reprap.org/read.php?147,99606), but now everything I've tried to print since then dies on this issue. I've had to go back to Sprinter.

**Comment by ErikZalm** [comment]
Pointedstick, Can you give some more information?
What HW and host are you using? Can you reproduce it? If so please pastbin the g-code and configuration.h so I can test it.

**Comment by Jaydmdigital** [comment]
Mine hung the other day, but I blamed Pronterface since I have not had the issue with Repsnapper. 

FWIW,
Jay

**Comment by Pointedstick** [comment]
Erik: of course, now I'm unable to reproduce the bug. :p I have another one related to the printer stopping at the beginning of a print, but I still need to regress it more before I blame Marlin and open an Issue.

**Comment by Atntias** [comment]
So i have news, i put the firmware on sanguinlulu 1.2 and is working great, yet on sanguinolulu 1.3 i get the same affect as for the gen3+, stuck after 2 commands, and olso again if jog it too fast (lots of clicks) get stuck.

i really want to debug this bug! its getting wierder every day, what shuold i test?!
 im olso in the irc so we can debug it online...

**Comment by ErikZalm** [comment]
Hello,

Did you tried the 0.9.10 version. Pushed it yesterday.

I am on IRC almost every evening. (CET) You can PM me.
My IRC alias is EvdZ.
(I am always online. But not always looking)

Best regards,

Erik van der Zalm

----- Original Message -----

**Comment by Atntias** [comment]
just tried the 0.9.10 same results, il try cach you on the irc to debug this.

**Comment by Atntias** [comment]
after some debugging we found that its probely that some bootloaders take bore space and therefore require a smaller buffer, so if changed BUFFSIZE on marlin.pde to 4 everything is working great! so im closeing the issue, and if you have similar problem try this solution!

**Comment by Pointedstick** [comment]
Sweet! This fixed the issue for me as well!

Nathaniel

**Comment by jdslabs** [comment]
Ran into this issue today on 0.9.10L. BUFSIZE was set to 8 by default...trying 4 and will report back.

**Comment by jdslabs** [comment]
So no change with v0.9.10L and a BUFSIZE of 4. I was using a baud rate of 250000. Same problem (if not quicker to occur) at 115200.

No problems with Sprinter.
